openapi: 3.0.1
info:
  title: Web Service Procesador de archivos
  description: |-
    Sistema de clasificación de documentos serverless compuesto por una Azure Function (proyectoancon) que procesa un documento enviado a través de la plataforma. Se procesa el archivo y, una vez realizado, se devuelve una respuesta en formato JSON con la información correspondiente al resultado del procesamiento.

    **Endpoint: proyectoancon**
    -  https://proyectoancon-fhgnbmanaweednd7.eastus-01.azurewebsites.net/api/http_trigger?code=Xxp0Krs3EiMCoXRPOisbk9QRcijYQVS14XhrQavTStGeAzFuALI60w%3D%3D
  version: 1.0.0

servers:
  - url: https://virtserver.swaggerhub.com/pucp-ada/proyectoancon-api/1.0.0
    description: SwaggerHub API Auto Mocking

paths:
  /api/http_trigger:
    post:
      summary: Integración que procesa y categoriza archivos PDF o imágenes
      parameters:
        - name: code
          in: query
          description: Clave de acceso de Azure Function (si aplica)
          required: false
          schema:
            type: string
            example: Xxp0Krs3EiMCoXRPOisbk9QRcijYQVS14XhrQavTStGeAzFuALI60w==
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/api_http_trigger_body"
      responses:
        "200":
          description: Respuesta con el resultado del análisis
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200"
              example:
                metadata:
                  processing_time_sec: 3.1033
                  file_processed: "009-1009137_7.jpeg"
                  num_pages: 1
                results:
                  - fileName: "009-1009137_7.jpg"
                    category: "Registro unico de propiedad vehicular (150)"
                    method: "Binario .jpg"
                    scores:
                      - 0.0006064571
                      - 3.6409434e-05
                      - 7.491013e-05
                      - 3.638905e-07
                      - 1.842311e-07
                      - 7.773299e-06
                      - 0.00027561063
                      - 0.0014523446
                      - 1.9042278e-06
                      - 0.9970626
                      - 0.00047591806
                      - 3.0150443e-07
                      - 1.4225467e-06
                      - 7.165576e-07
                      - 2.4642584e-06
                      - 4.4816573e
